"""Tools owned by the base package (every hat).

Generated by scripts/move_tool_branches.py from Agent._run_tool_call
(F-DRIVER Phase A); each registers itself with app.agents.core.tool_registry.
"""
from __future__ import annotations

from app.agents.core.tool_registry import ToolCall, tool


@tool("delegate_to_agent", owner="base", display_name='Specialist hand-off')
async def handle_delegate_to_agent(call: ToolCall) -> dict:
    """The ``delegate_to_agent`` tool."""
    from app.agents.runtime import (  # noqa: F401 -- runtime helpers, imported at call time
        AGENT_REGISTRY,
        MAX_DELEGATION_DEPTH,
        get_agent,
    )
    _call_stack = call.call_stack
    _depth = call.depth
    api_key = call.api_key
    args = call.args
    name = call.name
    project_id = call.project_id
    agent_name = args.get("agent_name") or ""
    message = args.get("message") or ""
    if _depth + 1 > MAX_DELEGATION_DEPTH:
        return {
            "name": name,
            "ok": False,
            "result": {
                "status": "error",
                "error": "delegation depth exceeded",
                "hint": f"Maximum delegation depth ({MAX_DELEGATION_DEPTH}) reached; answer directly.",
            },
        }
    target = get_agent(agent_name)
    from app.core.privileges import caller_may_use_agent
    if target is not None and not caller_may_use_agent(target):
        target = None
    if target is None:
        return {
            "name": name,
            "ok": False,
            "result": {
                "status": "error",
                "error": f"Unknown agent: {agent_name}",
                "hint": f"Valid agents: {', '.join(sorted(n for n, a in AGENT_REGISTRY.items() if caller_may_use_agent(a))) or '(none)'}.",
            },
        }
    if agent_name in _call_stack:
        return {
            "name": name,
            "ok": False,
            "result": {
                "status": "error",
                "error": "delegation loop detected",
                "hint": f"Delegation loop detected: agent '{agent_name}' is already in the delegation chain; answer directly.",
            },
        }
    sub = await target.chat(
        message,
        api_key=api_key,
        project_id=project_id,
        _depth=_depth + 1,
        _call_stack=_call_stack + [agent_name],
    )
    return {
        "name": "delegate_to_agent",
        "ok": True,
        "result": {
            "agent": agent_name,
            "answer": sub.get("answer"),
            "status": sub.get("status"),
        },
    }


@tool("search_project_documents", owner="base", display_name='Project document search')
async def handle_search_project_documents(call: ToolCall) -> dict:
    """The ``search_project_documents`` tool."""
    args = call.args
    name = call.name
    project_id = call.project_id
    if not project_id:
        return {
            "name": name,
            "ok": False,
            "result": {
                "status": "error",
                "error": "no project in scope",
                "hint": "This tool requires a project-scoped chat.",
            },
        }
    try:
        from app.core.doc_index import search_project_documents
    except ImportError as e:
        return {
            "name": name,
            "ok": False,
            "result": {
                "status": "error",
                "error": f"document search unavailable: {e}",
                "hint": "Document search is not available; proceed without it.",
            },
        }
    query = args.get("query") or ""
    top_k = args.get("top_k")
    # Some providers ship integer args as strings ("1" vs 1). Coerce
    # so the downstream sqlite LIMIT clause doesn't choke on a str.
    try:
        top_k = int(top_k) if top_k not in (None, "") else 5
    except (TypeError, ValueError):
        top_k = 5
    results = await search_project_documents(project_id, query, top_k)
    return {
        "name": "search_project_documents",
        "ok": True,
        "result": {"results": results},
    }


@tool("list_project_documents", owner="base", display_name='Project document list')
async def handle_list_project_documents(call: ToolCall) -> dict:
    """The ``list_project_documents`` tool."""
    from app.agents.runtime import (  # noqa: F401 -- runtime helpers, imported at call time
        _off_loop,
    )
    args = call.args
    name = call.name
    project_id = call.project_id
    if not project_id:
        return {
            "name": name,
            "ok": False,
            "result": {
                "status": "error",
                "error": "no project in scope",
                "hint": "This tool requires a project-scoped chat.",
            },
        }
    try:
        limit = int(args.get("limit") or 100)
    except (TypeError, ValueError):
        limit = 100
    limit = max(1, min(limit, 200))
    from app.core import projects as _projects_store
    # The pilot's master-corpus project is an alias with no documents
    # of its own — list the backing corpus, like the chat path does.
    resolved_pid = ((await _off_loop(_projects_store._master_corpus_source, project_id))
                    or project_id)
    docs = (await _off_loop(_projects_store.list_documents, resolved_pid, limit=limit, offset=0, newest_first=True,
    ))
    total = (await _off_loop(_projects_store.count_documents, resolved_pid))
    return {
        "name": "list_project_documents",
        "ok": True,
        "result": {
            "total_documents": total,
            "returned": len(docs),
            "documents": [
                {
                    "filename": d.get("original_name"),
                    "doc_type": d.get("doc_type"),
                    "size_bytes": d.get("size"),
                }
                for d in docs
            ],
        },
    }


@tool("fetch_document", owner="base", display_name='Document reader')
async def handle_fetch_document(call: ToolCall) -> dict:
    """The ``fetch_document`` tool."""
    from app.agents.runtime import (  # noqa: F401 -- runtime helpers, imported at call time
        _fetch_document_content,
        _off_loop,
    )
    args = call.args
    name = call.name
    project_id = call.project_id
    if not project_id:
        return {
            "name": name,
            "ok": False,
            "result": {
                "status": "error",
                "error": "no project in scope",
                "hint": "This tool requires a project-scoped chat.",
            },
        }
    doc_id = (args.get("document_id") or "").strip()
    filename = (args.get("filename") or "").strip()
    if not doc_id and not filename:
        return {
            "name": name,
            "ok": False,
            "result": {
                "status": "error",
                "error": "provide document_id or filename",
                "hint": "Pass the id from the attachment note or a search result, or the file's name.",
            },
        }
    content, doc, err = (await _off_loop(_fetch_document_content, project_id, doc_id, filename))
    if err:
        return {"name": name, "ok": False, "result": {"status": "error", "error": err}}
    return {
        "name": "fetch_document",
        "ok": True,
        "result": {
            "document_id": doc.get("id"),
            "filename": doc.get("original_name"),
            "doc_type": doc.get("doc_type"),
            "content": content["text"],
            "truncated": content["truncated"],
            "source": content["source"],
        },
    }


@tool("remember_fact", owner="base", display_name='Project memory')
async def handle_remember_fact(call: ToolCall) -> dict:
    """The ``remember_fact`` tool."""
    from app.agents.runtime import (  # noqa: F401 -- runtime helpers, imported at call time
        _off_loop,
    )
    args = call.args
    conversation_id = call.conversation_id
    project_id = call.project_id
    agent = call.agent
    from app.core import agent_memory
    key = args.get("key") or ""
    value = args.get("value") or ""
    (await _off_loop(agent_memory.set_agent_fact, agent.name, key, value, conversation_id, project_id
    ))
    return {
        "name": "remember_fact",
        "ok": True,
        "result": {
            "status": "success",
            "remembered": {key: value},
        },
    }


@tool("construction_calc", owner="base", display_name='Platform calculator')
async def handle_construction_calc(call: ToolCall) -> dict:
    """construction_calc (deterministic formula library)"""
    from app.agents.runtime import (  # noqa: F401 -- runtime helpers, imported at call time
        _ask_is_ipc_certificate,
        _defaulted_run_refusal,
        _dispatch_payment_certificate,
        _formula_calculator_name_from_message,
        _inject_user_ask_into_construction_calc_args,
        _off_loop,
    )
    args = call.args
    history = call.history
    user_message = call.user_message
    calc_name = (
        (args or {}).get("calculation")
        or (args or {}).get("name")
        or (args or {}).get("calculator")
    )
    if (
        not calc_name
        and _ask_is_ipc_certificate(user_message or "")
    ):
        return await _dispatch_payment_certificate(
            args, user_message=user_message,
        )
    # Live Phase-2: the model calls this tool with only
    # ``{"action": "construction_calc"}``. #663 extract reads
    # text/formula/message — inject the current user turn so
    # bind sees As1500 / span 8m / W=10000 kN. D7: never invent.
    args = _inject_user_ask_into_construction_calc_args(
        args, user_message, history=history,
    )
    if not calc_name:
        calc_name = (await _off_loop(_formula_calculator_name_from_message, str((args or {}).get("text") or user_message or ""),
        ))
    from app.lib import construction_formulas as _cf
    calc_params = _cf.coerce_calc_params(args.get("params"))
    # SHARED WITH AGENT C / #636 / #639 / #652: models put calculator
    # kwargs next to ``calculation`` instead of inside ``params``.
    # The container path already flattens; the tool path must too or
    # known names (excavation_bank_m3, volume, BCWS, PMI bcws/bcwp/acwp)
    # never reach run_calculation. Also covers E4 ``text`` / ``formula``.
    # Envelope keys (text/formula/input/project_id) are stripped
    # in bind_calculation_params — never passed as calc kwargs.
    # Unwrap ``input`` the same way as ``params`` (DIR7) — never copy
    # the envelope key itself as a calculator kwarg.
    _envelope = {
        "calculation", "name", "calculator", "params", "input",
        "project_id", "conversation_id", "user_id",
    }
    nested_input = _cf.coerce_calc_params(args.get("input"))
    if nested_input:
        for ik, iv in nested_input.items():
            if ik in _envelope:
                continue
            if ik in calc_params and calc_params[ik] not in (None, ""):
                continue
            if iv is None or iv == "":
                continue
            calc_params[ik] = iv
    for key, val in (args or {}).items():
        if key in _envelope:
            continue
        if key in calc_params and calc_params[key] not in (None, ""):
            continue
        if val is None or val == "":
            continue
        calc_params[key] = val
    refusal = _defaulted_run_refusal(calc_name, calc_params, user_message)
    if refusal is not None:
        return {"name": "construction_calc", "ok": True, "result": refusal}
    result = _cf.run_calculation(
        calc_name,
        calc_params,
    )
    return {
        "name": "construction_calc",
        "ok": isinstance(result, dict) and result.get("status") != "error",
        "result": result,
    }
