"""Tools owned by the planning hat.

Generated by scripts/move_tool_branches.py from Agent._run_tool_call
(F-DRIVER Phase A); each registers itself with app.agents.core.tool_registry.
"""
from __future__ import annotations

from app.agents.core.tool_registry import ToolCall, tool


@tool("generate_wbs", owner="planning")
async def handle_generate_wbs(call: ToolCall) -> dict:
    """generate_wbs (direct construction shortcut) Bypasses the generic "construction" tool's input/params ambiguity by giving the model a typed call: brief, target_count, project_type, start_date. Maps straight to ConstructionContainer.generate_wbs()"""
    from app.agents.runtime import (  # noqa: F401 -- runtime helpers, imported at call time
        message_is_contract_data_lookup,
        stage_conversation_wbs,
    )
    args = call.args
    conversation_id = call.conversation_id
    history = call.history
    name = call.name
    project_id = call.project_id
    agent = call.agent
    user_message = call.user_message
    if message_is_contract_data_lookup(user_message or ""):
        return {
            "name": name,
            "ok": False,
            "result": {
                "status": "error",
                "error": (
                    "This is a Contract Data lookup (Time for "
                    "Completion / milestones / similar). Do not "
                    "generate a WBS. Answer from retrieved contract "
                    "context."
                ),
            },
        }
    if "construction" not in agent.allowed_blocks:
        return {
            "name": name,
            "ok": False,
            "result": {
                "status": "error",
                "error": "construction container not in agent's allowed_blocks",
            },
        }
    try:
        from app.dependencies import get_block_instance
        container = get_block_instance("construction")
    except Exception as e:
        return {
            "name": name,
            "ok": False,
            "result": {"status": "error", "error": f"construction unavailable: {e}"},
        }
    # Coerce target_count if the provider shipped it as a string ("30" → 30).
    tc_raw = args.get("target_count", 200)
    try:
        tc = int(tc_raw) if tc_raw not in (None, "") else 200
    except (TypeError, ValueError):
        tc = 200
    from app.lib.wbs_duration_overrides import collect_overrides
    params = {
        "brief": args.get("brief") or user_message or "",
        "target_count": tc,
        "project_type": args.get("project_type"),
        "start_date": args.get("start_date"),
        "user_message": user_message,
        "history": history,
        "project_id": project_id,
        "duration_overrides": collect_overrides(
            user_message,
            args.get("brief"),
            explicit=args.get("duration_overrides"),
            history=history,
        ),
    }
    try:
        result = await container.generate_wbs({}, params)
    except Exception as e:
        return {
            "name": name,
            "ok": False,
            "result": {"status": "error", "error": f"generate_wbs failed: {e}"},
        }
    # Strip the activities array down before returning to the model —
    # 300+ rows × ~30 chars each = ~10 kB which the model doesn't need
    # to re-read into its context. The full list stays in the result
    # for any caller that does (the chat router's "end" event carries
    # tool_calls metadata; the activities themselves are reachable via
    # the /v1/execute API). The model just needs: counts, summary,
    # phase tree, assumptions, and a sample of activities to cite.
    if isinstance(result, dict) and isinstance(result.get("activities"), list):
        acts = result["activities"]
        # Bind the full activity list to this conversation BEFORE
        # stripping it from the model-facing payload.
        if conversation_id and result.get("status") == "success":
            stage_conversation_wbs(conversation_id, result)
        compact = dict(result)
        compact["activities_total"] = len(acts)
        compact["activities_sample"] = acts[:15]  # first 15 for reference
        # Drop the full activities array from what the model sees.
        compact.pop("activities", None)
        result = compact
    return {
        "name": "generate_wbs",
        "ok": isinstance(result, dict) and result.get("status") == "success",
        "result": result,
    }


@tool("resource_histogram", owner="planning")
async def handle_resource_histogram(call: ToolCall) -> dict:
    """The ``resource_histogram`` tool."""
    from app.agents.runtime import (  # noqa: F401 -- runtime helpers, imported at call time
        _off_loop,
        _resolve_file_path,
        _resolve_histogram_schedule_file,
        os,
    )
    args = call.args
    name = call.name
    project_id = call.project_id
    agent = call.agent
    user_message = call.user_message
    if "construction" not in agent.allowed_blocks:
        return {
            "name": name, "ok": False,
            "result": {
                "status": "error",
                "error": "construction container not in agent's allowed_blocks",
            },
        }
    try:
        from app.dependencies import get_block_instance
        container = get_block_instance("construction")
    except Exception as e:
        return {
            "name": name, "ok": False,
            "result": {"status": "error", "error": f"construction unavailable: {e}"},
        }
    raw = args.get("schedule_file") or args.get("file_path") or ""
    resolved = (await _off_loop(_resolve_file_path, project_id, raw)) if raw else ""
    if not resolved or not os.path.exists(str(resolved)):
        resolved, _picked = (await _off_loop(_resolve_histogram_schedule_file, project_id, user_message or "",
        ))
    if not resolved:
        return {
            "name": name, "ok": False,
            "result": {
                "status": "error",
                "error": (
                    "No schedule file resolved — name the .xer "
                    "(e.g. resource_loaded.xer) or upload one."
                ),
            },
        }
    period_unit = args.get("period_unit") or "week"
    try:
        result = await container.resource_histogram(
            {},
            {"schedule_file": resolved, "period_unit": period_unit},
        )
    except Exception as e:
        return {
            "name": name, "ok": False,
            "result": {
                "status": "error",
                "error": f"resource_histogram failed: {e}",
            },
        }
    return {
        "name": "resource_histogram",
        "ok": isinstance(result, dict) and result.get("status") == "success",
        "result": result,
    }


@tool("look_ahead", owner="planning")
async def handle_look_ahead(call: ToolCall) -> dict:
    """The ``look_ahead`` tool."""
    from app.agents.runtime import (  # noqa: F401 -- runtime helpers, imported at call time
        Any,
        _off_loop,
        _resolve_file_path,
        _resolve_histogram_schedule_file,
        os,
    )
    args = call.args
    name = call.name
    project_id = call.project_id
    agent = call.agent
    user_message = call.user_message
    if "construction" not in agent.allowed_blocks:
        return {
            "name": name, "ok": False,
            "result": {
                "status": "error",
                "error": "construction container not in agent's allowed_blocks",
            },
        }
    try:
        from app.dependencies import get_block_instance
        container = get_block_instance("construction")
    except Exception as e:
        return {
            "name": name, "ok": False,
            "result": {"status": "error", "error": f"construction unavailable: {e}"},
        }
    raw = args.get("schedule_file") or args.get("file_path") or ""
    resolved = (await _off_loop(_resolve_file_path, project_id, raw)) if raw else ""
    if not resolved or not os.path.exists(str(resolved)):
        resolved, _picked = (await _off_loop(_resolve_histogram_schedule_file, project_id, user_message or "",
        ))
    if not resolved and not args.get("activities"):
        return {
            "name": name, "ok": False,
            "result": {
                "status": "error",
                "error": (
                    "No schedule file resolved — name the .xer, "
                    "upload one, or list the activities."
                ),
            },
        }
    la_params: dict[str, Any] = {"schedule_file": resolved}
    if user_message:
        la_params["user_message"] = user_message
    for key in ("weeks", "days", "as_of", "data_date", "activities"):
        if args.get(key) is not None:
            la_params[key] = args.get(key)
    if la_params.get("as_of") is None and la_params.get("data_date") is None:
        from app.containers.construction.schedule import _stated_look_ahead_date
        stated = _stated_look_ahead_date(user_message or "")
        if stated:
            la_params["as_of"] = stated
    try:
        result = await container.look_ahead({}, la_params)
    except Exception as e:
        return {
            "name": name, "ok": False,
            "result": {
                "status": "error",
                "error": f"look_ahead failed: {e}",
            },
        }
    return {
        "name": "look_ahead",
        "ok": isinstance(result, dict) and result.get("status") == "success",
        "result": result,
    }
